// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: filter.proto
// Protobuf Java Version: 4.29.3

package com.project.proto;

public final class FilterRequestOuterClass {
  private FilterRequestOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      FilterRequestOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FilterRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.project.proto.FilterRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string customers = 1;</code>
     * @return A list containing the customers.
     */
    java.util.List<java.lang.String>
        getCustomersList();
    /**
     * <code>repeated string customers = 1;</code>
     * @return The count of customers.
     */
    int getCustomersCount();
    /**
     * <code>repeated string customers = 1;</code>
     * @param index The index of the element to return.
     * @return The customers at the given index.
     */
    java.lang.String getCustomers(int index);
    /**
     * <code>repeated string customers = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the customers at the given index.
     */
    com.google.protobuf.ByteString
        getCustomersBytes(int index);

    /**
     * <code>double minTotal = 2;</code>
     * @return The minTotal.
     */
    double getMinTotal();
  }
  /**
   * Protobuf type {@code com.project.proto.FilterRequest}
   */
  public static final class FilterRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.project.proto.FilterRequest)
      FilterRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 3,
        /* suffix= */ "",
        FilterRequest.class.getName());
    }
    // Use FilterRequest.newBuilder() to construct.
    private FilterRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private FilterRequest() {
      customers_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.project.proto.FilterRequestOuterClass.internal_static_com_project_proto_FilterRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.project.proto.FilterRequestOuterClass.internal_static_com_project_proto_FilterRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.project.proto.FilterRequestOuterClass.FilterRequest.class, com.project.proto.FilterRequestOuterClass.FilterRequest.Builder.class);
    }

    public static final int CUSTOMERS_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList customers_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string customers = 1;</code>
     * @return A list containing the customers.
     */
    public com.google.protobuf.ProtocolStringList
        getCustomersList() {
      return customers_;
    }
    /**
     * <code>repeated string customers = 1;</code>
     * @return The count of customers.
     */
    public int getCustomersCount() {
      return customers_.size();
    }
    /**
     * <code>repeated string customers = 1;</code>
     * @param index The index of the element to return.
     * @return The customers at the given index.
     */
    public java.lang.String getCustomers(int index) {
      return customers_.get(index);
    }
    /**
     * <code>repeated string customers = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the customers at the given index.
     */
    public com.google.protobuf.ByteString
        getCustomersBytes(int index) {
      return customers_.getByteString(index);
    }

    public static final int MINTOTAL_FIELD_NUMBER = 2;
    private double minTotal_ = 0D;
    /**
     * <code>double minTotal = 2;</code>
     * @return The minTotal.
     */
    @java.lang.Override
    public double getMinTotal() {
      return minTotal_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < customers_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, customers_.getRaw(i));
      }
      if (java.lang.Double.doubleToRawLongBits(minTotal_) != 0) {
        output.writeDouble(2, minTotal_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < customers_.size(); i++) {
          dataSize += computeStringSizeNoTag(customers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCustomersList().size();
      }
      if (java.lang.Double.doubleToRawLongBits(minTotal_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, minTotal_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.project.proto.FilterRequestOuterClass.FilterRequest)) {
        return super.equals(obj);
      }
      com.project.proto.FilterRequestOuterClass.FilterRequest other = (com.project.proto.FilterRequestOuterClass.FilterRequest) obj;

      if (!getCustomersList()
          .equals(other.getCustomersList())) return false;
      if (java.lang.Double.doubleToLongBits(getMinTotal())
          != java.lang.Double.doubleToLongBits(
              other.getMinTotal())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCustomersCount() > 0) {
        hash = (37 * hash) + CUSTOMERS_FIELD_NUMBER;
        hash = (53 * hash) + getCustomersList().hashCode();
      }
      hash = (37 * hash) + MINTOTAL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinTotal()));
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.project.proto.FilterRequestOuterClass.FilterRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.project.proto.FilterRequestOuterClass.FilterRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.project.proto.FilterRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.project.proto.FilterRequest)
        com.project.proto.FilterRequestOuterClass.FilterRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.project.proto.FilterRequestOuterClass.internal_static_com_project_proto_FilterRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.project.proto.FilterRequestOuterClass.internal_static_com_project_proto_FilterRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.project.proto.FilterRequestOuterClass.FilterRequest.class, com.project.proto.FilterRequestOuterClass.FilterRequest.Builder.class);
      }

      // Construct using com.project.proto.FilterRequestOuterClass.FilterRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        customers_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        minTotal_ = 0D;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.project.proto.FilterRequestOuterClass.internal_static_com_project_proto_FilterRequest_descriptor;
      }

      @java.lang.Override
      public com.project.proto.FilterRequestOuterClass.FilterRequest getDefaultInstanceForType() {
        return com.project.proto.FilterRequestOuterClass.FilterRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.project.proto.FilterRequestOuterClass.FilterRequest build() {
        com.project.proto.FilterRequestOuterClass.FilterRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.project.proto.FilterRequestOuterClass.FilterRequest buildPartial() {
        com.project.proto.FilterRequestOuterClass.FilterRequest result = new com.project.proto.FilterRequestOuterClass.FilterRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.project.proto.FilterRequestOuterClass.FilterRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          customers_.makeImmutable();
          result.customers_ = customers_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.minTotal_ = minTotal_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.project.proto.FilterRequestOuterClass.FilterRequest) {
          return mergeFrom((com.project.proto.FilterRequestOuterClass.FilterRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.project.proto.FilterRequestOuterClass.FilterRequest other) {
        if (other == com.project.proto.FilterRequestOuterClass.FilterRequest.getDefaultInstance()) return this;
        if (!other.customers_.isEmpty()) {
          if (customers_.isEmpty()) {
            customers_ = other.customers_;
            bitField0_ |= 0x00000001;
          } else {
            ensureCustomersIsMutable();
            customers_.addAll(other.customers_);
          }
          onChanged();
        }
        if (other.getMinTotal() != 0D) {
          setMinTotal(other.getMinTotal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureCustomersIsMutable();
                customers_.add(s);
                break;
              } // case 10
              case 17: {
                minTotal_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringArrayList customers_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCustomersIsMutable() {
        if (!customers_.isModifiable()) {
          customers_ = new com.google.protobuf.LazyStringArrayList(customers_);
        }
        bitField0_ |= 0x00000001;
      }
      /**
       * <code>repeated string customers = 1;</code>
       * @return A list containing the customers.
       */
      public com.google.protobuf.ProtocolStringList
          getCustomersList() {
        customers_.makeImmutable();
        return customers_;
      }
      /**
       * <code>repeated string customers = 1;</code>
       * @return The count of customers.
       */
      public int getCustomersCount() {
        return customers_.size();
      }
      /**
       * <code>repeated string customers = 1;</code>
       * @param index The index of the element to return.
       * @return The customers at the given index.
       */
      public java.lang.String getCustomers(int index) {
        return customers_.get(index);
      }
      /**
       * <code>repeated string customers = 1;</code>
       * @param index The index of the value to return.
       * @return The bytes of the customers at the given index.
       */
      public com.google.protobuf.ByteString
          getCustomersBytes(int index) {
        return customers_.getByteString(index);
      }
      /**
       * <code>repeated string customers = 1;</code>
       * @param index The index to set the value at.
       * @param value The customers to set.
       * @return This builder for chaining.
       */
      public Builder setCustomers(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCustomersIsMutable();
        customers_.set(index, value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string customers = 1;</code>
       * @param value The customers to add.
       * @return This builder for chaining.
       */
      public Builder addCustomers(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCustomersIsMutable();
        customers_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string customers = 1;</code>
       * @param values The customers to add.
       * @return This builder for chaining.
       */
      public Builder addAllCustomers(
          java.lang.Iterable<java.lang.String> values) {
        ensureCustomersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, customers_);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string customers = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustomers() {
        customers_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string customers = 1;</code>
       * @param value The bytes of the customers to add.
       * @return This builder for chaining.
       */
      public Builder addCustomersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCustomersIsMutable();
        customers_.add(value);
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private double minTotal_ ;
      /**
       * <code>double minTotal = 2;</code>
       * @return The minTotal.
       */
      @java.lang.Override
      public double getMinTotal() {
        return minTotal_;
      }
      /**
       * <code>double minTotal = 2;</code>
       * @param value The minTotal to set.
       * @return This builder for chaining.
       */
      public Builder setMinTotal(double value) {

        minTotal_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double minTotal = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinTotal() {
        bitField0_ = (bitField0_ & ~0x00000002);
        minTotal_ = 0D;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.project.proto.FilterRequest)
    }

    // @@protoc_insertion_point(class_scope:com.project.proto.FilterRequest)
    private static final com.project.proto.FilterRequestOuterClass.FilterRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.project.proto.FilterRequestOuterClass.FilterRequest();
    }

    public static com.project.proto.FilterRequestOuterClass.FilterRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FilterRequest>
        PARSER = new com.google.protobuf.AbstractParser<FilterRequest>() {
      @java.lang.Override
      public FilterRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FilterRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilterRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.project.proto.FilterRequestOuterClass.FilterRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_project_proto_FilterRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_project_proto_FilterRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014filter.proto\022\021com.project.proto\"4\n\rFil" +
      "terRequest\022\021\n\tcustomers\030\001 \003(\t\022\020\n\010minTota" +
      "l\030\002 \001(\001B,\n\021com.project.protoB\027FilterRequ" +
      "estOuterClassb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_project_proto_FilterRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_project_proto_FilterRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_project_proto_FilterRequest_descriptor,
        new java.lang.String[] { "Customers", "MinTotal", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
